### ISSUE TITLE
tagging

### ISSUE THREAD

**Issue by markdingemanse** [jameswmcnab/config-yaml#2]
I would like to use this package in a production environment but i would like to refrain from having a dev-master with a specific commit in my composer file. Would it be possible to  give the 5.2 version of this package a fixed tag. Thank you in advance.

**Comment by jameswmcnab** [comment]
No problem I've tagged a v2.1.0 release that is Laravel 5.2 compatible that you can pull in with

``` json
"jameswmcnab/config-yaml": "^2.1"
```

I've also started on some much needed updates to the package that will either be a v2.2 or v3.0 release depending on if I can prevent BC breaks or not.

**Comment by markdingemanse** [comment]
Thank you.
